backend:
  name: git-gateway
  branch: main # confira se no seu github é 'main' ou 'master'

media_folder: "images"
public_folder: "/images"

collections:
  - name: "servicos"
    label: "Serviços Realizados"
    folder: "content/servicos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título do Serviço", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Foto do Trabalho", name: "image", widget: "image" }
      - { label: "Descrição", name: "body", widget: "markdown" }
